# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  ## Disable auto update of VirtualBox Guest Additions
  config.vbguest.auto_update = false

  ## Lab 1
  config.vm.define "lab1" do |subconfig|
    # Set box and hostname
    subconfig.vm.box = "ubuntu/jammy64"    
    subconfig.vm.hostname = "lab1"
    # Set up networks
    subconfig.vm.network "private_network",
      ip: "192.168.3.2", 
      virtualbox__intnet: "intnet1"
    subconfig.vm.provider "virtualbox" do |vb|
      # Custom VM Group, memory, and CPU cores
      vb.customize ["modifyvm", :id, "--groups", "/lab"]
      vb.customize ["modifyvm", :id, "--memory", "1024"]
      vb.customize ["modifyvm", :id, "--cpus", "14"]
    end
    # (0..3).each do |i|
      # subconfig.vm.disk :disk, size: "1GB", name: "disk-#{i}"
    subconfig.vm.disk :disk, size: '1GB', name: 'raidDisk1'
    subconfig.vm.disk :disk, size: '1GB', name: 'raidDisk2'
    subconfig.vm.disk :disk, size: '1GB', name: 'raidDisk3'
    # end
    # Add provisioning scripts
    subconfig.vm.provision "shell", inline: <<-SHELL
      sudo echo "192.168.3.3 lab2" | sudo tee -a /etc/hosts
      sudo sed -i 's/archive.ubuntu./fi.archive.ubuntu./g' /etc/apt/sources.list
      sudo apt update
      sudo apt install -y net-tools
    SHELL
    subconfig.vm.provision :shell, privileged: false, path: "scripts/lab1.sh"
  end

  ## Lab 2
  config.vm.define "lab2" do |subconfig|
    # Set box and hostname
    subconfig.vm.box = "ubuntu/jammy64"
    subconfig.vm.hostname = "lab2"
    # Set up networks
    subconfig.vm.network "private_network",
      ip: "192.168.3.3", 
      virtualbox__intnet: "intnet1"
    subconfig.vm.provider "virtualbox" do |vb|
      # Custom VM Group, memory, and CPU cores
      vb.customize ["modifyvm", :id, "--groups", "/lab"]
      vb.customize ["modifyvm", :id, "--memory", "1024"]
      vb.customize ["modifyvm", :id, "--cpus", "14"]
    end
    # Add provisioning scripts
    subconfig.vm.provision "shell", inline: <<-SHELL
      sudo echo "192.168.3.2 lab1" | sudo tee -a /etc/hosts
      sudo sed -i 's/archive.ubuntu./fi.archive.ubuntu./g' /etc/apt/sources.list
      sudo apt update
      sudo apt install -y net-tools
    SHELL
    subconfig.vm.provision :shell, privileged: false, path: "scripts/lab2.sh"
  end
end
