# -*- mode: ruby -*-
# vi: set ft=ruby :
ENV["LC_ALL"] = "en_US.UTF-8"

## Documentation for VirtualBox-specific features:
# https://www.vagrantup.com/docs/providers/virtualbox/networking
# VirtualBox networking: https://www.virtualbox.org/manual/ch06.html
# modifyvm command: https://www.virtualbox.org/manual/ch08.html#vboxmanage-modifyvm

Vagrant.configure("2") do |config|
  ## Disable auto update of VirtualBox Guest Additions
  config.vbguest.auto_update = false

  ## Lab 1
  config.vm.define "lab1" do |subconfig|
    # Set box and hostname
    subconfig.vm.box = "ubuntu/jammy64"    
    subconfig.vm.hostname = "lab1"
    # Set up networks
    subconfig.vm.network "private_network",
      ip: "192.168.0.2",
      netmask:"255.255.255.0",
      virtualbox__intnet: "intnet1"
    subconfig.vm.network "private_network",
      ip: "192.168.2.2",
      virtualbox__intnet: "intnet2"
    subconfig.vm.provider "virtualbox" do |vb|
      # Custom VM Group, memory, and CPU cores
      vb.customize ["modifyvm", :id, "--groups", "/lab"]
      vb.customize ["modifyvm", :id, "--memory", "4096"]
      vb.customize ["modifyvm", :id, "--cpus", "14"]
      # enable promiscuous mode on the network
      vb.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
      vb.customize ["modifyvm", :id, "--nicpromisc3", "allow-all"]
    end
    # Add provisioning scripts
    subconfig.vm.provision "shell", inline: <<-SHELL
      sudo echo "192.168.0.3 lab2" | sudo tee -a /etc/hosts
      sudo echo "192.168.2.3 lab3" | sudo tee -a /etc/hosts
      sudo apt update
      sudo apt install -y net-tools inetutils-traceroute nmap openvpn bridge-utils
    SHELL
    subconfig.vm.provision :shell, privileged: false, path: "scripts/lab1.sh"
  end

  ## Lab 2
  config.vm.define "lab2" do |subconfig|
    # Set box and hostname
    subconfig.vm.box = "ubuntu/jammy64"
    subconfig.vm.hostname = "lab2"
    # Set up networks
    subconfig.vm.network "private_network",
      ip: "192.168.0.3",
      netmask:"255.255.255.0",
      virtualbox__intnet: "intnet1"
    subconfig.vm.provider "virtualbox" do |vb|
      # Custom VM Group, memory, and CPU cores
      vb.customize ["modifyvm", :id, "--groups", "/lab"]
      vb.customize ["modifyvm", :id, "--memory", "4096"]
      vb.customize ["modifyvm", :id, "--cpus", "14"]
      # enable promiscuous mode on the network
      vb.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
    end
    # Add provisioning scripts
    subconfig.vm.provision "shell", inline: <<-SHELL
      sudo echo "192.168.0.2 lab1" | sudo tee -a /etc/hosts
      sudo echo "192.168.2.3 lab3" | sudo tee -a /etc/hosts
      sudo apt update
      sudo apt install -y net-tools inetutils-traceroute nmap openvpn bridge-utils
    SHELL
    subconfig.vm.provision :shell, privileged: false, path: "scripts/lab2.sh"
  end

  ## Lab 3
  config.vm.define "lab3" do |subconfig|
    # Set box and hostname
    subconfig.vm.box = "ubuntu/jammy64"
    subconfig.vm.hostname = "lab3"
    # Set up networks
    subconfig.vm.network "private_network",
      ip: "192.168.2.3",
      netmask:"255.255.255.0",
      virtualbox__intnet: "intnet2"
    subconfig.vm.provider "virtualbox" do |vb|
      # Custom VM Group, memory, and CPU cores
      vb.customize ["modifyvm", :id, "--groups", "/lab"]
      vb.customize ["modifyvm", :id, "--memory", "4096"]
      vb.customize ["modifyvm", :id, "--cpus", "14"]
      # enable promiscuous mode on the network
      vb.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
    end
    # Add provisioning scripts
    subconfig.vm.provision "shell", inline: <<-SHELL
      sudo echo "192.168.2.2 lab1" | sudo tee -a /etc/hosts
      sudo echo "192.168.0.3 lab2" | sudo tee -a /etc/hosts
      sudo apt update
      sudo apt install -y net-tools inetutils-traceroute nmap openvpn bridge-utils
    SHELL
    subconfig.vm.provision :shell, privileged: false, path: "scripts/lab3.sh"
  end
end